### ISSUE TITLE
is there any solution for this?

### ISSUE THREAD

**Issue by yumidev00** [MetaStag/awesome-dots#2]
![dV3WzG0](https://user-images.githubusercontent.com/82706323/132136797-9dcd2333-86a8-4bee-a89a-96cb0b104235.png)

**Comment by metastag** [comment]
sorry for the late reply,
Solution for what? Do you want to hide that systray? Or the corner radius.
The systray is manipulated by all the 6 variables starting with `tray-` in the config file, you can edit them to see how it changes.
You can find all the options [here](https://github.com/polybar/polybar/wiki/Configuration#bar-settings) (search for "tray" using ctrl+f)

**Comment by yumidev00** [comment]
ill just hide it then) 
![ad](https://user-images.githubusercontent.com/82706323/132251168-3b46a105-c69c-4108-8d19-27eb87801d91.png)
